server:
  port: 9090
spring:
  application:
    name: organisationservice
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/configserver/
  cloud:
   config:
    enabled: true
    eureka:
     instance:
      preferIpAddress: true
    client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
   com.zaxxer.hikari: info
